<x-admin-layout>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam labore unde, molestias vero ab nihil itaque harum sint odit accusamus tempore sed quidem alias odio blanditiis? Libero reprehenderit repudiandae atque?</p>
    <p>Laborum totam ea, similique ut voluptates rem dolore dolorum iste tenetur dolor minima magni consequatur quis a cum eum laudantium ipsum natus velit saepe sint placeat enim provident! Voluptatibus, modi.</p>
    <p>Fuga voluptate, facilis nemo, alias suscipit similique fugiat est explicabo perspiciatis porro ut tempora facere fugit eaque repellendus laborum molestiae ullam nisi nesciunt vitae dignissimos enim quia. Maiores, fugit nisi.</p>
    <p>Numquam nemo expedita consequuntur. Animi quos delectus expedita non omnis ad ut, voluptatum maxime deleniti architecto, ex corrupti doloribus, qui hic debitis. Officiis earum facilis cupiditate, distinctio dolorem praesentium nostrum.</p>
    <p>Nesciunt sint provident praesentium fuga at veritatis quo perferendis nisi eligendi, doloremque cum illum sit laboriosam sapiente nemo esse delectus ullam ipsam impedit amet aut quis similique animi. Dignissimos, recusandae!</p>
    <p>Sit commodi cumque reiciendis expedita placeat deserunt dicta quasi iure dolore eligendi officiis adipisci aut molestiae consectetur obcaecati sequi necessitatibus earum, ex praesentium quas laborum voluptatum corrupti asperiores. Cumque, dolor!</p>
    <p>Distinctio amet, reprehenderit, laborum placeat corporis, quos architecto explicabo doloremque culpa voluptatem quas rerum repudiandae incidunt reiciendis. Adipisci laudantium dolores repellendus, dolore, architecto aperiam quos soluta minima ullam tempora beatae?</p>
    <p>Exercitationem earum ipsam dicta iste sint excepturi, voluptate modi obcaecati ad autem officia molestiae unde minima, distinctio deserunt cumque? Earum consequuntur mollitia soluta vero dignissimos quae accusantium alias non illum!</p>
    <p>Nemo, odio quaerat illum iure ad laudantium ipsa enim et eius saepe libero officiis, aspernatur quia praesentium vero quasi hic autem atque eum laboriosam explicabo porro tempora omnis? Enim, expedita.</p>
    <p>Repellendus itaque porro dolore? Optio est perferendis earum iste accusamus vitae dolorum illo aut. Esse alias natus dolorem ipsam soluta quia dolorum maxime nesciunt minima velit dolores molestias, consequuntur maiores.</p>
    <p>A quisquam non quasi magnam, ratione tenetur ad minus consequuntur. Vero corrupti optio voluptate ratione sint placeat recusandae repellat aut quaerat labore. Architecto, voluptatum sed voluptate iste ipsa officiis eaque.</p>
    <p>Blanditiis totam laudantium deleniti voluptatum excepturi odit ea pariatur voluptate rerum, et nobis aliquid ex exercitationem, dolorum debitis adipisci illo sint! Mollitia blanditiis assumenda nobis similique itaque! Aut, error nobis.</p>
    <p>Qui deserunt, iure quas, laudantium mollitia tempora harum, commodi consequuntur sit deleniti sunt illo autem aut maiores! Minus rerum iste dolorum quo, molestiae inventore velit quidem pariatur accusantium qui ullam.</p>
    <p>Voluptas, vitae aperiam minima adipisci veniam vero quos dolor eaque, dolore, iste quas reprehenderit doloremque. Excepturi, quam corrupti possimus magni fugit consectetur obcaecati! Laboriosam odit dolorem vero, accusantium quis placeat!</p>
    <p>Distinctio voluptatem quae saepe enim incidunt ea deserunt quo laboriosam ullam, quod non quos quisquam sunt, optio repudiandae? Eveniet ut recusandae possimus enim aut asperiores alias consequuntur laborum repellat minima!</p>
    <p>Provident natus aliquid et quo eius porro unde, illo sunt quibusdam, fuga, officiis ipsa debitis recusandae tempore repellendus dolore aperiam. Doloremque mollitia aliquid est alias deserunt dolores natus eaque numquam!</p>
    <p>At aspernatur, quis maxime facilis placeat quisquam ex a, nobis cumque labore esse, reiciendis vel magni odit repellendus ipsam non officiis. Error, nisi debitis nam ratione saepe ipsam quibusdam quod.</p>
    <p>Velit laboriosam doloribus tempora sunt officiis sint consequuntur quis in iure natus atque, optio animi expedita corporis et assumenda alias illo modi id. Voluptas sit, eligendi aspernatur repellat corporis doloribus?</p>
    <p>Consequuntur, est, odit necessitatibus repudiandae nihil eveniet aliquid asperiores, vitae molestiae laboriosam doloremque unde minima eum delectus odio incidunt? Adipisci, pariatur voluptatum. Velit a quo nihil recusandae ratione, dicta ab.</p>
    <p>Ratione incidunt porro, adipisci delectus modi vero culpa, beatae eveniet ad expedita a nihil ab sed natus quae ducimus perspiciatis laboriosam repellendus vitae reiciendis nam, commodi consequatur! Harum, aut mollitia.</p>

</x-admin-layout>